In [1]:
import numpy as np
import cv2
from PIL import Image
from Algorithm import key_expansion, ciphering_block, key_update, deciphering_block
from Image import blockshaped, From_blocks_to_arr_image
from Metrics import Entr, Hist, EQ

In [2]:
k1 = [1,32,3,234,15,156,7,8,9,40,1,2,3,43,5,64]
k2 = [1,2,35,54,55,26,73,8,9,50,21,2,3,45,5,65]
k3 = [1,27,3,24,25,6,7,8,9,0,13,2,23,4,5,64]
k4 = [143,25,33,4,5,6,73,8,39,0,1,2,3,4,5,6]

img_path = 'station.jpg'
img = cv2.imread(img_path, 0)

imgb = blockshaped(img, 16, 16)
Nb = len(imgb)
imgb_c = [0] * Nb
imgb_d = [0] * Nb

key_B = key_expansion(k1, k2, k3, k4)

for i in range(Nb):
    B = imgb[i]
    B_C = ciphering_block(B, key_B, 8)
    imgb_c[i] = B_C
    key_B = key_update(key_B, B_C, B, k1, k2, k3, k4, 8)

In [3]:
print(key_B) # ключ шифрования первого блока (дальше обновляем в key_update)

[[76, 35, 72, 27, 150, 93, 26, 173, 27, 115, 77, 23, 165, 114, 135, 115], [145, 42, 13, 184, 229, 202, 217, 29, 191, 135, 85, 63, 10, 195, 14, 162], [113, 2, 1, 160, 67, 128, 138, 24, 241, 207, 248, 242, 23, 127, 126, 76], [16, 22, 228, 112, 235, 29, 252, 54, 188, 245, 65, 49, 60, 40, 233, 215], [139, 27, 111, 189, 74, 188, 91, 142, 238, 103, 231, 160, 253, 229, 153, 193], [192, 155, 166, 119, 252, 182, 110, 62, 117, 166, 147, 166, 211, 227, 62, 117], [229, 199, 5, 176, 156, 24, 48, 47, 165, 45, 254, 154, 236, 206, 169, 119], [55, 255, 153, 90, 40, 93, 148, 229, 150, 14, 26, 160, 72, 206, 127, 191], [86, 11, 34, 218, 191, 192, 190, 244, 18, 74, 231, 239, 67, 160, 15, 208], [98, 46, 77, 4, 204, 69, 146, 254, 32, 230, 146, 230, 50, 33, 213, 163], [202, 156, 234, 23, 166, 69, 172, 97, 94, 129, 78, 73, 176, 103, 181, 212], [20, 176, 214, 116, 239, 34, 55, 138, 162, 163, 174, 119, 101, 42, 25, 112], [137, 20, 215, 186, 149, 101, 135, 144, 96, 148, 198, 240, 197, 53, 246, 107], [167, 248, 14

In [4]:
print(imgb_c[2]) # Зашифрованный блок 16 х 16

[[136 148 211  75  70 206  77 159 241 145 199  17 173  72 235  12]
 [153 210 210 230 130 191 127 119 253  45 133  85 131 251  33 172]
 [131  46  13 232 228  33  30  99  91 219 165  29 235 248  68 135]
 [154 232  39  39 220 133 201  62 161 138 229   7 128  10 186  62]
 [217 242 141 107 234 226 216 173  33  21  69 108 196  58 130 238]
 [ 91 146 113  91 186  38 166  58 207 184 247  10 180 145  54 206]
 [183  11 136  51  33 120  68 208 177 234 117  85  95 248  27 163]
 [125   9 161  93 211 124 202 255  70 251  31 204   7  57  41 126]
 [ 19 101 154  88  34   4 103 191  83 251 197  82 231 122  94 212]
 [125  10 238 132   8 151 209 160 134 253 231 128  79 107  71  57]
 [233 186 213  10  99  41  38 108 229 235 239 113 173  72 218  19]
 [175 170 253  58   7 206 188 169  73 113 190  95  42  57 142  30]
 [110  51  26 243 119  32  24  42 104  19 175  59  85 115 208 219]
 [197 101 205  20 129 217  12 126 113  92 147 234  64  77 136 236]
 [192  43  90 133 248 108 239 121 100  19 144 102 201 170 130 

In [5]:
print(imgb[47]) # Исходный блок 16 х 16

[[23 27 32 37 41 43 43 43 42 42 42 42 42 42 42 42]
 [23 26 32 37 41 43 43 42 42 42 42 42 42 42 42 42]
 [23 26 32 37 41 43 43 42 41 41 42 42 42 42 42 42]
 [23 26 32 37 41 43 43 42 41 41 41 41 42 42 42 42]
 [23 26 32 37 41 43 43 42 41 41 41 41 41 41 42 42]
 [23 26 31 37 41 42 42 42 41 41 41 41 41 41 41 41]
 [22 26 31 37 41 42 42 42 40 40 41 41 41 41 41 41]
 [22 26 31 37 41 42 42 42 40 40 40 41 41 41 41 41]
 [23 26 31 36 39 41 40 40 40 40 40 40 40 40 40 40]
 [23 26 31 36 39 40 40 39 40 40 40 40 40 40 40 40]
 [22 25 30 35 38 40 39 39 39 39 39 39 39 39 39 39]
 [21 24 29 34 38 39 38 38 38 38 38 38 38 38 38 38]
 [20 24 29 34 37 38 38 37 37 37 37 37 37 37 37 37]
 [20 23 28 33 36 37 37 36 36 36 36 36 36 36 36 36]
 [19 22 27 32 36 37 36 36 36 36 36 36 36 36 36 36]
 [19 22 27 32 35 36 36 35 35 35 35 35 35 35 35 35]]


In [6]:
# дешифрование зашифрованной картинки
for i in range(Nb):
    B_C = imgb_c[i]
    B_D = deciphering_block(B_C, key_B, 8)
    imgb_d[i] = B_D
    key_B = key_update(key_B, B_C, B_D, k1, k2, k3, k4, 8)

In [7]:
print(imgb_d[47]) # Дешифрованный блок 16 х 16 (получен из imgb_c в ходе дешифровки)

[[ 10 159 129  47  51 165  22  76 186  90 221 127 239 156 122 119]
 [ 25  39  49 238 187 111  48  13  82 244 254  89 179 131  56  39]
 [230 253 242 140 133 106 104 162 135 103  19 240 185   4 230 205]
 [ 14   7  83  30 107  40 187  96  73 227  51 136 235  55 118 243]
 [ 62  86 140 133  65 205 255  36 243 148 237 241 197 185  96  45]
 [255 219 210 125  12 105  63  51  23 228 197 220 135 131 185 233]
 [  6 129 155  63  30 162  65 216  19 139 111 208   1 148 162 217]
 [ 29 225 254  50  26  44 232  16 169 172 173  32 252 144  40 181]
 [ 10   2  27 101 197 171 143  83  58 199 217 155 193  42 226 224]
 [106  26  32 105   8 118 255 213  50 128 232  29 240  68 207 138]
 [157 112   3 143  11 241 126 126 133 139  54 144  45  50 105  17]
 [214 104 107 198 211 190  94  22 136 151  18  85 185  57  32 175]
 [141 239  43 124 176 174  34  12 108 216 148 243  25 125 215  47]
 [ 34 113 134 229 200 115 142  82  84 190 153 100   9  64  73 221]
 [196 109 199 121 171 203 154 206 184 246  15 184  43 189 231 

In [10]:
k = int(len(img[0]) / 16)

arr2 = From_blocks_to_arr_image(imgb_d,Nb,k)

im_1 = Image.fromarray(arr2, 'L')
im_1.save("dencrypted.jpg")

In [9]:
EQ(img, arr2, 8)

579.5